export const socialStabilityMetrics = {
    decryptCacheHits: 0,
    decryptCacheMisses: 0,
    decryptCacheErrors: 0,
    liveFlagsCacheHits: 0,
    liveFlagsCacheMisses: 0,
    dailyMissionsFlagCacheHits: 0,
    dailyMissionsFlagCacheMisses: 0,
    scheduledLockAcquired: 0,
    scheduledLockSkipped: 0,
    friendExpiryLockAcquired: 0,
    friendExpiryLockSkipped: 0,
    streamAutoStartAttempts: 0,
    streamAutoStartSucceeded: 0,
    streamAutoStartSkipped: 0,
    streamAutoStartFailed: 0,
    callBalanceWarningsEmitted: 0,
    callBalanceExhaustedEnded: 0,
    notificationQueueEnqueued: 0,
    notificationQueueDeduplicated: 0,
    notificationQueueRetries: 0,
    notificationQueueDropped: 0,
    notificationQueueDispatchSuccess: 0,
    notificationQueueDispatchFailures: 0,
    notificationQueueDeadLettered: 0,
};

export type SocialStabilityMetricKey = keyof typeof socialStabilityMetrics;
